### ISSUE TITLE
Special character error

### ISSUE THREAD

**Issue by cyberfish** [shameerc/TextPress#12]
If I write special characters like 'ä, ö, ü, ß' inside the arrays in article.txt, I see the following errors. (The article.txts are formated and saved in utf-8.) If I change this special characters with html-code like '&szlig', I see errors, when I call the rss-feed.

<b>Warning: array_key_exists() expects parameter 2 to be array, null given in
/is/htdocs/wp.../www/.../lib/Textpress/Textpress.php on line 219</b>
<b>
Warning: array_key_exists() expects parameter 2 to be array, null given in
/is/htdocs/wp.../www/.../lib/Textpress/Textpress.php on line 555</b>

<pre>{
 "title":"Stra&szlig:enbahnhof",
.
.
}</pre>

**Comment by ralerstein** [comment]
I think the error has occurred by the difference between the PHP_EOL and the LineFeed codes in text files. 
So, it will disappear when LineFeed codes in text files changed to CR+LF. 

thank you.

**Comment by shameerc** [comment]
PHP_EOL is the line feed for the platform you are using. It may break when you write posts in windows machine and hosts in linux machine.
