### ISSUE TITLE
Object of class Textpress\Tag could not be converted to string

### ISSUE THREAD

**Issue by dinResita** [shameerc/TextPress#35]
Hi shameerc,

I extended layout_home.php to get the tags displayed
===
<div class="tags">
       <?php
	foreach ($global['tags'] as $slug => $tag) {
		echo '<a tabindex="-1" href="' . $global["base.url"] . '/tag/'.$slug.'">'. $tag .'</a>';
	}
	?>
</div>
===

Now I receive following error message:
===
Details
Type: ErrorException
Code: 4096
Message: Object of class Textpress\Tag could not be converted to string
File: /var/www/nginx/sitename/blog/themes/centum/layout_home.php
Line: 230
Trace
#0 /var/www/nginx/sitename/blog/themes/centum/layout_home.php(230): Slim\Slim::handleErrors(4096, 'Object of class...', '/var/www/nginx/...', 230, Array)
#1 /var/www/nginx/sitename/blog/src/shameerc/Textpress/View.php(107): require('/var/www/nginx/...')
#2 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/View.php(255): Textpress\View->render('index', NULL)
#3 /var/www/nginx/sitename/blog/src/shameerc/Textpress/View.php(82): Slim\View->fetch('index', NULL)
#4 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Slim.php(757): Textpress\View->display('index')
#5 /var/www/nginx/sitename/blog/src/shameerc/Textpress/Textpress.php(645): Slim\Slim->render('index', Array)
#6 /var/www/nginx/sitename/blog/src/shameerc/Textpress/Textpress.php(442): Textpress\Textpress->render('index')
#7 [internal function]: Textpress\{closure}()
#8 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Route.php(462): call_user_func_array(Object(Closure), Array)
#9 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Slim.php(1326): Slim\Route->dispatch()
#10 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#11 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 /var/www/nginx/sitename/blog/vendor/slim/slim/Slim/Slim.php(1271): Slim\Middleware\PrettyExceptions->call()
#14 /var/www/nginx/sitename/blog/src/shameerc/Textpress/Textpress.php(655): Slim\Slim->run()
#15 /var/www/nginx/sitename/blog/index.php(31): Textpress\Textpress->run()
#16 {main}
===

The layout_home.php is for tags is similar with the one for categories. How can I correct the error?

Best regards

**Comment by shameerc** [comment]
Each tag is an object of class [Tag](https://github.com/shameerc/TextPress/blob/master/src/shameerc/Textpress/Tag.php), with name and count attribute. An example use is `echo $tag->name . '  (' . $tag->count .')';` to show the name and count. 
Also see how it is used in article.php template file. https://github.com/shameerc/TextPress/blob/master/themes/textpress/article.php#L18

**Comment by dinResita** [comment]
Thanks shameerc,
it did work.

You may consider including the tags into layout.php and layout_home.php. I did adjust a little bit the syntax because in your example I got only the tags specific to the opened article.

    <?php
        foreach ($global['tags'] as $slug => $tag) {
            echo '<a href="/tag/' , $slug ,'">' , $tag->name , "</a>";
        }
    ?>

**Comment by shameerc** [comment]
Good suggestion. Thanks! 
I might also want to add a __toString() for tags
